# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aab5823bd4d890e9fc7841c955c0f5c9371ab55102f28e3cac5b12bfce12ab61c74973562e78a743ce09114e4940f8caf6aac01d263a230dbcf8ba0444328c29

test:
  secret_key_base: 0bc570096988721a5c6ce915e30f19c824fbbb39ba7665935a2f9feb39eaded155f0de8b77fa58b8d366c70147356ae181c95eb035b17f4e44c608718479c451

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
